// <auto-generated />
using System;
using GameAnalyticCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameAnalyticCore.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20221208114026_UpdateDB")]
    partial class UpdateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GameAnalyticCore.Models.Events", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Event_Day")
                        .HasColumnType("int");

                    b.Property<int>("Event_Month")
                        .HasColumnType("int");

                    b.Property<string>("Event_Week")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Event_Year")
                        .HasColumnType("int");

                    b.Property<int>("Game_Metric_Score_1")
                        .HasColumnType("int");

                    b.Property<int>("Game_Metric_Score_2")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("GameAnalyticCore.Models.GameUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("GameUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
